spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092   # sirf ye

  mail:
    host: smtp.gmail.com
    port: 587
    username: astikyadav4@gmail.com
    password: kjwtvcqjmcfxzkth
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  threads:
    virtual:
      enabled: true

server:
  port: 8082

app:
  kafka:
    topics:
      user-registered: user.registered
      email-verification: user.email.verification
      password-reset: user.password.reset
  mail:
    from: astikyadav4@gmail.com
    from-name: "Ecommerce App"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.astik.notification_service: DEBUG
    org.springframework.kafka: INFO
    org.springframework.mail: DEBUG