package com.astik.user_service.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGOUT,
    USER_LOGIN_FAILED,
    USER_UPDATED,
    USER_DELETED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    TOKEN_REFRESHED,
    ACCOUNT_LOCKED,
    EMAIL_VERIFIED
}
