package com.astik.user_service.enums;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    ROLE_CHANGE,
    STATUS_CHANGE,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    PHONE_VERIFIED,
    PROFILE_PICTURE_UPDATED,
    TOKEN_REFRESHED
}
