name: Spring Boot CI + Docker

on:
  push:
    branches: ["main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t springboot-api:latest .

      - name: Save Docker Image
        run: docker save springboot-api:latest -o springboot-api.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: springboot-api.tar
