name: User Service CI + Docker

on:
  push:
    branches: ["master"]
    paths:
      - 'user-service/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests
        working-directory: user-service

      - name: Build Docker Image
        run: docker build -t user-service:latest .
        working-directory: user-service

      - name: Save Docker Image
        run: docker save user-service:latest -o user-service.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-service-image
          path: user-service.tar